config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  # If not signin -> /
  # Else -> /dashboard

  # get 'signup' => 'users#new'

  # scope ':github_user/:repo' do
  #   resources :reviews, only: [:index]
  # end

  resources :reviews, only: [:show]

  post 'reviews' => "reviews#create"
end

## GET /:github_user/:repo/reviews
# Show all checks for the given user & repo.
#-----------------------------
#       |<:pr> <status>| <- clickable
#       |<:pr> <status>|
#       |<:pr> <status>|
#       |              |
#       |              |
#       |              |
#-----------------------------

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :lint
  belongs_to :review
end

app/models/lint.rb
class Lint < ActiveRecord::Base
  has_one :check
end

app/models/review.rb
class Review < ActiveRecord::Base
  has_many :checks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ReviewsHelper

  skip_before_filter :verify_authenticity_token, only: [:create]

  def show
    @review = Review.find(params[:id])
    @passed = @review.checks.all? { |check| check.passed }
  end

  def create
    if %w(open reopened synchronize).include? params.fetch(:pull_request, {})[:state]
      @payload = params[:pull_request]
      verify
    else
      render status: 500, body: 'invalid state'
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'GitHub PR Lintian'

    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  class VerifyError < Exception
  end

  TYPES = %w(feat fix perf chore misc refactor style docs version revert tests ci)
  ACCESS_TOKEN = '897a587a1d31faef9c7e46a97b21ab72048e9e42' # ENV['LINTHUB_TOKEN']

  class CommitSubjectLengthCheck
    def initialize(message, options = {})
      @message = message
      @limit = options[:limit] || 50
    end

    def index
      0
    end

    def execute
      @message.length <= @limit
    end
  end

  def verify
    repo = @payload[:base][:repo][:full_name]
    hash = @payload[:head][:sha]

    @client ||= Octokit::Client.new(access_token: ACCESS_TOKEN)
    @client.create_status(repo, hash, 'pending', context: 'linthub', description: 'The LintHub check is pending ...')

    commits = @client.pull_request_commits(@payload[:base][:repo][:full_name], @payload[:number])

    @review = Review.create
    @review.github_user = @payload[:base][:repo][:owner][:login]
    @review.repo = @payload[:base][:repo][:name]

    commits.each do |commit|
      checks = [CommitSubjectLengthCheck.new(commit[:commit][:message].lines.first.chomp)]
      checks.each do |check|
        result = check.execute

        @review.checks.create(
          github_user: @review.github_user,
          repo:        @review.repo,
          sha:         commit[:sha],
          passed:      result,
          lint_id:     check.index
        )
      end
    end
    @review.save

    if @review.checks.all? { |check| check.passed }
      @client.create_status(repo, hash, 'success', context: 'linthub', description: 'The LintHub check passed')
    else
      @client.create_status(repo, hash, 'error',   context: 'linthub', description: 'The LintHub check failed', target_url: review_url(@review))
    end
  end
end

# class ChecksController < ApplicationController
#   skip_before_filter :verify_authenticity_token, only: [:create]
#
#   def create
#     @client ||= Octokit::Client.new(access_token: ACCESS_TOKEN)
#
#     @payload = JSON.parse(params[:payload], symbolize_names: true)
#
#     if request.env['HTTP_X_GITHUB_EVENT'] == 'pull_request' && %w(opened reopened synchronize).include?(@payload[:action])
#       @check = Check.create
#
#       pull_request = @payload[:pull_request]
#
#       repo = pull_request[:base][:repo][:full_name]
#       hash = pull_request[:head][:sha]
#       context = 'gittools'
#       # verify 'gittools', pull_request do
#       begin
#         @client.create_status(repo, hash, 'pending', context: context, description: 'The GitTools check is pending ...')
#         commits = @client.pull_request_commits(pull_request[:base][:repo][:full_name], pull_request[:number])
#
#         commits.each do |commit|
#           if commit[:commit][:message].length >= LIMITS[:subject]
#             @check.lints.create(sha: commit[:sha], description: 'the subject line must fit in 50 characters')
#           end
#
#           message = commit[:commit][:message]
#           match = message.match(/(?<type>[[:alpha:]]+)\((?<scope>[[:alpha:]]+)\)\:.+/) || Hash.new
#
#           unless TYPES.include? match[:type]
#             @check.lints.create(sha: commit[:sha], description: 'type requirements are not met')
#           end
#
#           unless match[:scope].length > 16
#             @check.lints.create(sha: commit[:sha], description: 'scope requirements are not met')
#           end
#         end
#
#         fail VerifyError if @check.lints.length > 0
#         @client.create_status(repo, hash, 'success', context: context, description: 'The GitTools check passed')
#       rescue Exception => err
#         puts err: err
#         @client.create_status(repo, hash, 'error', context: context, description: 'The GitTools check failed', target_url:  check_url(id: @check.id, repo: pull_request[:base][:repo][:name], user: pull_request[:base][:repo][:owner][:login]))
#       end
#
#       @check.save
#     end
#
#     render status: 200
#   end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "LintHub", '#', id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",   '#' %></li>
                <li><%= link_to "Help",   '#' %></li>
                <li><%= link_to "Log in", '#' %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>

<body>
    <%= render 'layouts/header' %>

    <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
        <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
</body>
</html>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/show.html.erb
<div class="row">
    <div class="col-md-10">
        <h3>
            <%= @review.github_user %>/<%= @review.repo %>
        </h3>
    </div>
    <div class="col-md-2">
        <h3>
            <span class="label label-<%= @passed ? "success" : "danger" %>"><%= @passed ? "Success" : "Failure" %></span>
        </h3>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>SHA</th>
        </tr>
    </thead>

    <tbody>
        <% @review.checks.each do |check| %>
        <tr class=<%= check.passed ? "success" : "danger"%>>
            <td><%= check.lint.description %></td>
            <td><%= check.sha %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>